#!/bin/bash

# Initialize dry run mode as true
dry_run=true

# Function to display messages
info() {
  echo "[INFO] $1"
}

# Function to execute commands
execute() {
    if [ "$dry_run" = true ]; then
        echo "DRY RUN: $@"
    else
        $@
    fi
}

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --run) dry_run=false ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

install_brew_formulas() {  
  local formulas=$*  
  for formula in $formulas; do  
    if brew list --formula | grep -q "$formula"; then  
      info "Formula $formula is already installed."  
    else  
      info "Installing package < $formula >"  
      # Use execute function to handle dry run or actual installation
      execute brew install "$formula"  
    fi  
  done  
}

install_brew_casks() {  
  local casks=$*  
  for cask in $casks; do  
    if brew list --casks | grep -q "$cask"; then  
      info "Cask $cask is already installed."  
    else  
      info "Installing cask < $cask >"  
      # Use execute function to handle dry run or actual installation
      execute brew install --cask "$cask"  
    fi  
  done  
}

# Install casks  
apps=(kitty font-hack-nerd-font alfred alt-tab)  
install_brew_casks "${apps[@]}"

# Install formulas  
packages=(ripgrep rsync pandoc git-delta git zsh yarn xclip tree tree-sitter httpie htop lolcat mysql mas tmux nginx neovim node nmap nvm jq wget curl bat wdiff snappy sqlite)  
install_brew_formulas "${packages[@]}"

